version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    parameters:
      wagtail-version:
        default: "wagtail"
        type: string
      python-version:
        default: "3.12"
        type: string
    executor:
      name: python/default
      tag: "<< parameters.python-version >>"
    steps:
      - checkout
      - restore_cache:
          key: pip-{{ .Branch }}-<< parameters.wagtail-version >>-<< parameters.django-version >>-py<< parameters.python-version >>
      - run: pip install "<< parameters.django-version >>" "<< parameters.wagtail-version >>"
      - run: pip install -e .
      - save_cache:
          key: pip-{{ .Branch }}-<< parameters.wagtail-version >>-<< parameters.django-version >>-py<< parameters.python-version >>
          paths:
            - "~/.cache/pip"
      - run:
          command: ./runtests.py
          name: Test

  nightly-wagtail-test:
    parameters:
      python-version:
        default: "3.12"
        type: string
    executor:
      name: python/default
      tag: "<< parameters.python-version >>"
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/wagtail.git
      - run: pip install -e .
      - run: pip install ./wagtail
      - run: ./runtests.py
      - run:
          when: on_fail
          command: python ./.circleci/report_nightly_build_failure.py

workflows:
  main:
    jobs:
      - build-and-test:
          wagtail-version: "wagtail>=5.2,<5.3"
          django-version: "django>=4.2,<5.0"
          python-version: "3.9"
      - build-and-test:
          wagtail-version: "wagtail>=6.0,<6.1"
          django-version: "django>=5.0,<5.1"
          python-version: "3.12"
      - build-and-test:
          wagtail-version: "wagtail>=6.1,<6.2"
          django-version: "django>=5.0,<5.1"
          python-version: "3.12"
      - build-and-test:
          wagtail-version: "wagtail>=6.2,<6.3"
          django-version: "django>=5.0,<5.1"
          python-version: "3.12"
      - build-and-test:
          wagtail-version: "wagtail>=6.3,<6.4"
          django-version: "django>=5.2,<5.3"
          python-version: "3.12"
  nightly:
    jobs:
      - nightly-wagtail-test
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
