# Generated by Django 2.2.7 on 2019-12-09 13:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('tests', '0005_pagewithstreamfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithParentalManyToMany',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('ads', modelcluster.fields.ParentalManyToManyField(to='tests.Advert')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
