# Generated by Django 2.2.7 on 2019-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_pagewithparentalmanytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithManyToMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ManyToManyField(to='tests.Advert')),
            ],
        ),
    ]
