# Generated by Django 3.0.4 on 2020-03-25 17:38

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_pagewithrelatedpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewithstreamfield',
            name='body',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(max_length=250))])), ('page', wagtail.blocks.PageChooserBlock()), ('stream', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock())])), ('rich_text', wagtail.blocks.RichTextBlock()), ('list_of_pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], blank=True, verbose_name='Page body'),
        ),
    ]
