# Generated by Django 3.0.4 on 2020-03-30 10:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_pagechooserblock_nonrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewithrichtext',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
