# Generated by Django 3.0.4 on 2020-03-30 10:25

from django.db import migrations
from wagtail import VERSION as WAGTAIL_VERSION

if WAGTAIL_VERSION >= (3, 0):
    import wagtail.fields as wagtail_fields
else:
    import wagtail.core.fields as wagtail_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_pagechooserblock_nonrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewithrichtext',
            name='body',
            field=wagtail_fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
