# Generated by Django 3.0.5 on 2020-10-16 11:13

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tests', '0015_longadvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
