# Generated by Django 3.0.11 on 2020-12-22 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_advert_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='run_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='run_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
