# Generated by Django 4.0 on 2022-06-09 15:17

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_correctmodeltypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewithrelatedpages',
            name='related_pages',
            field=models.ManyToManyField(related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='pagewithstreamfield',
            name='body',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(max_length=250))])), ('integer', wagtail.blocks.IntegerBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock()), ('stream', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock())])), ('rich_text', wagtail.blocks.RichTextBlock()), ('list_of_pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock())), ('list_of_captioned_pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(max_length=250))])))], blank=True, verbose_name='Page body', use_json_field=True),
        ),
    ]
